[app]
log_level = "debug" # Level can be debug|info.
public_file = "/public/hello.txt"
required_packages = ["nginx", "curl", "supervisorctl"]

[server]
address = ":8080" # Interface/Port to bind.
name = "monschool-agent"
read_timeout="30s"
write_timeout="30s"
keepalive_timeout="60s"
max_body_size=10000 #10KB
read_buffer_size=10000 #10KB
